### ISSUE TITLE
Unable to build the project in android studio

### ISSUE THREAD

**Issue by kaustavguru** [KAlO2/PerfectShow#10]
Can you please guide me as to how to load the project in android studio.And which project to load iShow or perfectshow. 
I am unable to build the project

**Comment by KAlO2** [comment]
Previously I develop it with Eclipse, and not too long ago, I switched it to Android Studio project in respond to some guys' request. I think you should learn Android development first, there is no need to rush. Maybe you are missing OpenCV dependency library.
