### ISSUE TITLE
同时应用眉毛和眼睫毛

### ISSUE THREAD

**Issue by elva7073** [KAlO2/PerfectShow#15]
Hi,

请教一个问题，如果我同时应用眉毛和眼睫毛的texture会发现只有一个能用，另一个会失效，这是什么原因呢？

**Comment by KAlO2** [comment]
算不上 texture，还没有用到 OpenGL 相关的东西，只是一些 bitmap 的合成。
只有一个能用，可能是没有拿应用眉毛后的图跟将要合成眼睫毛的图合成，即每次都是用原图合成的，所以失效。
