### ISSUE TITLE
I can't Find this file please help me

### ISSUE THREAD

**Issue by vishmayleeway** [KAlO2/PerfectShow#7]
Hello

Error:(48, 0) studio\PerfectShow-master\iShow\src\main\cpp\Application.mk: No such file or directory
<a href="openFile:D:\sdk\sdk\ndk-bundle\build\core\add-application.mk">Open File</a>

**Comment by KAlO2** [comment]
Application.mk is already there in the project.
Bet you have space(s) in your directory, I will check it later if the scripts have this problem.
