### ISSUE TITLE
Cannot build and create gpuimage .so file

### ISSUE THREAD

**Issue by shubhwicked** [KAlO2/PerfectShow#9]

**Comment by KAlO2** [comment]
Hello, fellows,
gpuimage is from [here](https://github.com/BradLarson/GPUImage)
This project doesn't use GPUImage currently, so you can just remove it. I assume you know how to do this.

In fact, I've tried to use this module for dynamic makeup, where you save the makeup parameters from a static image, then use those parameters for dynamic makeup with front camera, like Meitu(美图秀秀) or tiantianPitu(天天P图) did in the apps. Hey, this is a fancy idea.

**Comment by shubhwicked** [comment]
Hello dear,
  Thanks for the idea you have given regarding the dynamic makeup with front camera, can you provide more detail regarding this, so i can implement it. How you had achieved it, at this sound so confusing for me. 
It will be very helpful, if you can help me a little bit in this.

**Comment by z0rgoyok** [comment]
Can you share your dynamic-makeup code?
